# Generated by Django 4.0.10 on 2023-07-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_enroll',
            field=models.BooleanField(default=False),
        ),
    ]
