# Generated by Django 4.0.10 on 2023-07-20 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
        ('users', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='title',
            new_name='ScheduleTitle',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='time',
            new_name='when',
        ),
        migrations.AddField(
            model_name='report',
            name='ScheduleType',
            field=models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report', to='boards.board'),
        ),
    ]
