# Generated by Django 4.0.10 on 2023-07-22 02:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_title_report_scheduletitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selected_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
