# Generated by Django 4.0.10 on 2023-07-22 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_selected_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='selected_time',
        ),
    ]
