# Generated by Django 4.0.10 on 2023-07-22 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_when'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='when',
            new_name='selected_time',
        ),
    ]
