databases:
  - name: v2.1_myfavor_back
    databaseName: v2.1_myfavor_back
    user: v2.1_myfavor_back
    region: singapore

services:
  - type: web
    name: v2.1_myfavor_back
    env: python
    region: singapore
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: v2.1_myfavor_back
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4