# Generated by Django 4.0.10 on 2023-06-25 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idols', '0003_idol_viewcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('enter', models.CharField(blank=True, max_length=40, null=True)),
                ('solo_profile', models.URLField(blank=True, max_length=100000, null=True)),
                ('member', models.ForeignKey(blank=True, max_length=40, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idol_solo', to='idols.idol')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
