# Generated by Django 4.0.10 on 2023-06-25 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solo',
            name='solo_debut',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
