# Generated by Django 4.0.10 on 2023-06-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solos', '0002_solo_solo_debut'),
    ]

    operations = [
        migrations.AddField(
            model_name='solo',
            name='solo_insta',
            field=models.URLField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='solo',
            name='solo_youtube',
            field=models.URLField(blank=True, max_length=10000, null=True),
        ),
    ]
