# Generated by Django 4.0.10 on 2023-07-03 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solos', '0003_solo_solo_insta_solo_solo_youtube'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solo',
            options={'verbose_name_plural': 'Idols_Solo'},
        ),
    ]
