# Generated by Django 4.0.10 on 2023-06-01 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idol',
            name='Boy_group',
        ),
        migrations.RemoveField(
            model_name='idol',
            name='Girl_group',
        ),
        migrations.RemoveField(
            model_name='idol',
            name='idol_solo',
        ),
    ]
