# Generated by Django 4.0.10 on 2023-07-16 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idol',
            old_name='viewCount',
            new_name='pickCount',
        ),
    ]
