# Generated by Django 4.0.10 on 2023-06-01 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0002_remove_idol_boy_group_remove_idol_girl_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idol',
            name='idol_debut',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
