# Generated by Django 4.0.10 on 2023-06-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idol',
            name='viewCount',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
