# Generated by Django 4.0.10 on 2023-06-02 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0003_idol_idol_debut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idol',
            name='idol_gender',
            field=models.BooleanField(default=False),
        ),
    ]
