# Generated by Django 4.0.10 on 2023-07-17 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0003_rename_viewcount_idol_pickcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idol',
            name='pickCount',
        ),
    ]
