# Generated by Django 4.0.10 on 2023-06-25 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0004_alter_idol_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idol',
            name='idol_debut',
        ),
    ]
