# Generated by Django 4.1.7 on 2023-06-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0005_idol_has_scheduels'),
    ]

    operations = [
        migrations.AddField(
            model_name='idol',
            name='is_solo',
            field=models.BooleanField(default=False),
        ),
    ]
