# Generated by Django 4.1.7 on 2023-06-02 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0006_idol_is_solo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idol',
            name='idol_birthday',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='idol',
            name='idol_gender',
            field=models.CharField(choices=[('Woman', 'Woman'), ('Man', 'Man')], max_length=50),
        ),
    ]
