# Generated by Django 4.1.7 on 2023-06-02 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0007_alter_idol_idol_birthday_alter_idol_idol_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idol',
            name='idol_gender',
        ),
    ]
