# Generated by Django 4.1.7 on 2023-06-05 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0008_remove_idol_idol_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idol',
            old_name='has_scheduels',
            new_name='has_schedules',
        ),
        migrations.RemoveField(
            model_name='idol',
            name='idol_anniv',
        ),
    ]
