# Generated by Django 4.1.7 on 2023-06-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0011_rename_groups_group'),
        ('idols', '0010_idol_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idol',
            name='group',
            field=models.ManyToManyField(related_name='idols', to='groups.group'),
        ),
    ]
