# Generated by Django 4.0.10 on 2023-07-09 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(blank=True, max_length=100, null=True)),
                ('album_cover', models.URLField(blank=True, max_length=100000, null=True)),
                ('release_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
