# Generated by Django 4.0.10 on 2023-06-01 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idols', '0003_idol_idol_debut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('idol_name_en', models.ManyToManyField(blank=True, related_name='prize_idol_en', to='idols.idol')),
                ('idol_name_kr', models.ManyToManyField(blank=True, related_name='prize_idol_kr', to='idols.idol')),
            ],
            options={
                'verbose_name_plural': 'Prizes',
            },
        ),
    ]
