# Generated by Django 4.1.7 on 2023-06-08 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idols', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('idol_name', models.ManyToManyField(blank=True, related_name='prize_idol', to='idols.idol')),
            ],
            options={
                'verbose_name_plural': 'Prizes',
            },
        ),
    ]
