# Generated by Django 4.0.10 on 2023-06-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0003_idol_idol_debut'),
        ('prizes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prize',
            name='idol_name_en',
        ),
        migrations.RemoveField(
            model_name='prize',
            name='idol_name_kr',
        ),
        migrations.AddField(
            model_name='prize',
            name='idol_name',
            field=models.ManyToManyField(blank=True, related_name='prize_idol', to='idols.idol'),
        ),
    ]
