# Generated by Django 4.1.7 on 2023-06-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='content',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
    ]
