# Generated by Django 4.0.10 on 2023-07-27 02:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter', models.CharField(blank=True, max_length=40, null=True)),
                ('groupname', models.CharField(blank=True, max_length=40, null=True)),
                ('group_profile', models.URLField(blank=True, max_length=10000, null=True)),
                ('group_debut', models.DateField(default=datetime.date.today)),
                ('group_insta', models.URLField(blank=True, max_length=10000, null=True)),
                ('group_youtube', models.URLField(blank=True, max_length=10000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Idols_Group',
            },
        ),
    ]
