# Generated by Django 4.0.10 on 2023-06-01 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idols', '0002_remove_idol_boy_group_remove_idol_girl_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belong', models.CharField(blank=True, choices=[('SmTown', 'SmTown'), ('YG', 'YG'), ('JYP', 'JYP'), ('HYBE', 'HYBE'), ('MBK', 'MBK'), ('StoneMusic', 'StoneMusic'), ('CUBE', 'CUBE'), ('Mistic', 'Mistic')], max_length=40, null=True)),
                ('Girl_group', models.CharField(blank=True, choices=[('ASEPA', 'ASEPA'), ('AKMU', 'AKMU'), ('BLACKPINK', 'BLACKPINK'), ('ITZY', 'ITZY'), ('BILLLIE', 'BILLLIE'), ('NEWJEANS', 'NEWJEANS'), ('LESSERAFIM', 'LESSERAFIM'), ('CELEBFIVE', 'CELEBFIVE'), ('CHOBOM', 'CHOBOM'), ('GIDLE', 'GIDLE'), ('CLASSY', 'CLASSY'), ('DAVICHI', 'DAVICHI'), ('FROMIS_9', 'FROMIS_9')], max_length=40, null=True)),
                ('Boy_group', models.CharField(blank=True, choices=[('AB6IX', 'AB6IX'), ('AKMU', 'AKMU'), ('BTOB', 'BTOB'), ('BTS', 'BTS'), ('DAY_6', 'DAY6'), ('EXO', 'EXO'), ('HIGH_LIGHT', 'HIGH_LIGHT')], max_length=40, null=True)),
                ('idol_solo', models.CharField(blank=True, choices=[('GirlSolo', 'GirlSolo'), ('BoySolo', 'BoySolo')], max_length=40, null=True)),
                ('idol_name_en', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups_idol_en', to='idols.idol')),
                ('idol_name_kr', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups_idol_kr', to='idols.idol')),
            ],
            options={
                'verbose_name_plural': 'Idols_Group',
            },
        ),
    ]
