# Generated by Django 4.0.10 on 2023-06-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter', models.CharField(blank=True, max_length=40, null=True)),
                ('groupname', models.CharField(blank=True, max_length=40, null=True)),
                ('group_profile', models.URLField(blank=True, max_length=10000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Idols_Group',
            },
        ),
    ]
