# Generated by Django 4.0.10 on 2023-06-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('idols', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='member',
            field=models.ManyToManyField(null=True, related_name='groups', to='idols.idol'),
        ),
    ]
