# Generated by Django 4.0.10 on 2023-06-01 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0002_remove_idol_boy_group_remove_idol_girl_group_and_more'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='idol_name_en',
            field=models.ForeignKey(default='', max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups_idol_en', to='idols.idol'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='idol_name_kr',
            field=models.ForeignKey(default='', max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups_idol_kr', to='idols.idol'),
        ),
    ]
