# Generated by Django 4.0.10 on 2023-06-25 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_debut',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='group',
            name='group_insta',
            field=models.URLField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='group_youtube',
            field=models.URLField(blank=True, max_length=10000, null=True),
        ),
    ]
