# Generated by Django 4.0.10 on 2023-06-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_groups_idol_name_en_alter_groups_idol_name_kr'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='group_profile',
            field=models.URLField(blank=True, max_length=10000, null=True),
        ),
    ]
