# Generated by Django 4.0.10 on 2023-06-01 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0003_idol_idol_debut'),
        ('groups', '0003_groups_group_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='idol_name_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups_idol_en', to='idols.idol'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='idol_name_kr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups_idol_kr', to='idols.idol'),
        ),
    ]
