# Generated by Django 4.0.10 on 2023-06-01 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0003_idol_idol_debut'),
        ('groups', '0004_alter_groups_idol_name_en_alter_groups_idol_name_kr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='idol_name_en',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='idol_name_kr',
        ),
        migrations.AddField(
            model_name='groups',
            name='idol_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups_idol', to='idols.idol'),
        ),
    ]
