# Generated by Django 4.0.10 on 2023-06-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0003_idol_idol_debut'),
        ('groups', '0005_remove_groups_idol_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='idol_name',
        ),
        migrations.AddField(
            model_name='groups',
            name='idol_name',
            field=models.ManyToManyField(null=True, related_name='groups_idol', to='idols.idol'),
        ),
    ]
