# Generated by Django 4.0.10 on 2023-06-02 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_remove_groups_idol_name_groups_idol_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='idol_name',
            new_name='idol',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='idol_solo',
        ),
        migrations.AddField(
            model_name='groups',
            name='is_solo',
            field=models.BooleanField(default=False),
        ),
    ]
