# Generated by Django 4.0.10 on 2023-06-02 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_rename_idol_name_groups_idol_remove_groups_idol_solo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='idol',
            new_name='member',
        ),
    ]
