# Generated by Django 4.1.7 on 2023-06-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_remove_groups_is_solo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='Boy_group',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='Girl_group',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='belong',
        ),
        migrations.AddField(
            model_name='groups',
            name='enter',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='groups',
            name='groupname',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
