# Generated by Django 4.1.7 on 2023-06-05 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0009_rename_has_scheduels_idol_has_schedules_and_more'),
        ('groups', '0010_remove_groups_boy_group_remove_groups_girl_group_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groups',
            new_name='Group',
        ),
    ]
