# Generated by Django 4.1.7 on 2023-06-06 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0011_alter_idol_group'),
        ('groups', '0011_rename_groups_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='member',
            field=models.ManyToManyField(null=True, related_name='groups', to='idols.idol'),
        ),
    ]
