# Generated by Django 4.0.10 on 2023-06-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='type',
            field=models.CharField(blank=True, choices=[('broadcast', 'BROADCAST'), ('event', 'EVENT'), ('release', 'RELEASE'), ('congrats', 'CONGRATS'), ('buy', 'BUY')], default='', max_length=15),
        ),
    ]
