# Generated by Django 4.0.10 on 2023-07-27 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('schedules', '0001_initial'),
        ('idols', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to='users.report'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='participant',
            field=models.ManyToManyField(blank=True, max_length=150, related_name='schedules', to='idols.idol'),
        ),
    ]
